### ISSUE TITLE
Proper example for the user.create ?

### ISSUE THREAD

**Issue by bakman2** [blargoner/jshue#11]
I am not sure what I am doing incorrectly, but I only get errors when creating a user.

```
var user = hue.bridge('10.0.0.162').user('bakman');

// create user account (requires link button to be pressed)

user.create('bakman huetest', 
	function(success){
	
		console.log(success)
	},
	function(error){
		console.log(error)

	}
	);
```
```
[{"error":{"type":7,"address":"/username","description":"invalid value, bakman, for parameter, username"}}]
```

**Comment by bakman2** [comment]
I have create a user via the debug console of the hue bridge. Not sure why it didn't work with jshue.

**Comment by blargoner** [comment]
@bakman2 The problem is that your username "bakman" is too short (shorter than 10 characters). If you try to create that same username from the debug console, you will get the same error:
 
<img width="560" alt="bakman" src="https://cloud.githubusercontent.com/assets/91284/9151684/e94de206-3dd9-11e5-9102-4f54b7f8cb92.png">

So this is not a bug with jsHue, it is just passing that error back from the bridge.

However, it looks like the Hue API will soon no longer allow custom usernames to be created, so I will need to add a bridge method which allows you to retrieve a randomly generated username from the bridge.

**Comment by bakman2** [comment]
Yeah I should have read the api first. Didn't know it required 10 chars. Thanks
