### ISSUE TITLE
Sample for getting data from HUE bridge

### ISSUE THREAD

**Issue by vwpeter** [blargoner/jshue#13]
I managed to control lamps and schedules via java script. 
e.g.     user.setSchedule(sched, { status: "disabled" }, function(data) { /* ... */ });

But how can I get information from the bridge?
Tried this, but it didn't work:   user.getSchedule(sched, function(data) { st = data[0].status; });

Thank you very much!
Peter

**Comment by blargoner** [comment]
That doesn't work because the response data from that API command is not an array. It would be:

```js
user.getSchedule(sched, function(data) { st = data.status });
```

Please read the API documentation [here](http://www.developers.meethue.com/documentation/schedules-api-0), and experiment with the debugger, in order to understand the data structures that should be sent and received.
